### ISSUE TITLE
Weird XML formating in browser when using alternate languages

### ISSUE THREAD

**Issue by gerrit-de-heij** [blendinteractive/Blend.Sitemap.Umbraco#5]
I have a multilingual site and would like to generate an XML sitemap. When the sitemap is generated, I get a weird formatting:

![image](https://github.com/blendinteractive/Blend.Sitemap.Umbraco/assets/152879100/60ccb9cc-3bf0-43af-b32f-3d003095205a)

This is what the code looks like in the inspector:"

![image](https://github.com/blendinteractive/Blend.Sitemap.Umbraco/assets/152879100/4fa127f9-6d88-4dd5-b76d-89b58c443e63)

I did some research and found [this StackOverflow question](https://stackoverflow.com/questions/45274063/xml-format-in-browsers-when-added-xhtml). The answer says that this can be fixed by changing "http" to "https" in the following line in the sitemap: `xmlns:xhtml="http://www.w3.org/1999/xhtml"`.

I can't edit this in the Sitemap.cshtml file because this is generated everytime the application is started. Is there a way that I can fix this?

Thanks in advance!

**Comment by chase-burandt** [comment]
I have taken a look and I have it on my schedule to update the package next week.
I'll push out an update to 10, 11, & 13 versions.

**Comment by chase-burandt** [comment]
I have pushed out an update to fix the Urls to use https. This is currently on 13.0.2

I will eventually get a push out for version 10 & 11, I have to update the workflow so that I can push to those previous versions.

**Comment by gerrit-de-heij** [comment]
Thanks, It works now!
