### ISSUE TITLE
ChangeFrequency and Priority can't be turned off, contrary to documentation claims

### ISSUE THREAD

**Issue by supernaut** [blendinteractive/Blend.Sitemap.Umbraco#9]
The documentation says the following:

> `Sitemap.DocumentType.ChangeFrequency` is an optional string. Options for this are `always`, `hourly`, `daily`, `weekly`, `monthly`, `yearly`, and `never`. If not filled in these document types will not have the property.
> 
> `Sitemap.DocumentType.Priority` is an optional string. Options for this are `0.1` thorugh `0.9` and `1.0`. If not filled in these document types will not have the property.

I interpret this as if I omit these fields from my config, these document types will not get the fields `ChangeFrequency` or `Priority` in the generated sitemap. This is not true. If omitted, both fall back to default values and no empty or null values are accepted.

I would suggest either implement the functionality as I interpret the documentation claims, or clarify the documentation.

**Comment by TPofahl** [comment]
Thanks @supernaut, I created a PR for this issue to get this resolved. The changes in the PR will remove changefreq and priority from the sitemap when they are not specified in the appSettings.
[ https://github.com/blendinteractive/Blend.Sitemap.Umbraco/pull/11 ](https://github.com/blendinteractive/Blend.Sitemap.Umbraco/pull/11)

**Comment by chase-burandt** [comment]
This has been merged in.
